### PR TITLE
Add Quilt Mappings support

### PR DESCRIPTION
**Pull request by IotaBread**
Update to Loom 0.9, update Quiltflower to 1.5.0, change task group to Quilt, un-hardcode some constants. Tests still need updating.

### CODE REVIEW

**Comment by i509VCB** [comment]
I think it would be more appropriate to have 0.9 on a branch for 0.9 instead of merging it into 0.8.

Also doesn't 0.9 add a requirement to have Java 16 if I recall?

**Comment by IotaBread** [comment]
I agree. I merged `FabricMC/dev/0.9` into `QuiltMC/dev/0.8` because the latter had some work done on it. I have [a branch without the QM support](https://github.com/ByMartrixx/quilt-loom/tree/merge-upstream) that could be merged into a new dev/0.9, which this pr would then target.

And yes, loom 0.9 does require Java 16, but still can be used for Java 8 mods by setting `sourceCompatibility` and `targetCompatibility` in a mod's buildscript to Java 8.
I still can open a PR with QM support for 0.8 if you want

**Comment by Siuolplex** [comment]
This is really useful for me since Im making some early quilt mods. When I get home I'll test and see if it works. Thank you!

**Comment by TheGlitch76** [comment]
I'm doing a fresh restart of this loom fork, sorry! Please cherry-pick this back on to dev/0.10

**Pull request closed without merging**
